route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'

  routes:
    - match:
        severity: ' critical '
      receiver: 'email-alert'
      group_wait: 10s
      repeat_interval: 5m
    - match:
        severity: ' warning '
      receiver: 'slack-alert'
      group_wait: 5s
      repeat_interval: 5m

receivers:
  - name: 'default-receiver'  # default receiver for other severity labels
    email_configs:
      - to: xyz@gmail.com
        from: abc@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: abc@gmail.com
        auth_password:  auth-code # replace with your own code
        require_tls: true
        send_resolved: true

  - name: 'email-alert'
    email_configs:
      - to: xyz@gmail.com
        from: abc@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: abc@gmail.com
        auth_password: auth-code # replace with your own code
        require_tls: true
        send_resolved: true

  - name: 'slack-alert'
    slack_configs:
      - api_url: 'https://test-url'  # replace with your Slack webhook URL
        channel: '#alerts'  # replace with your Slack channel
        send_resolved: true 
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'
