{
 "title": "Host System Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(instance,job) (irate(node_cpu_seconds_total{job=\"exporter\",instance=\"192.168.11.130:9100\",mode!=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": " node_memory_MemTotal_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"} - node_memory_MemFree_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"} - node_memory_Cached_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"} - node_memory_Buffers_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"}",
     "legendFormat": "cached"
    },
    {
     "expr": " node_memory_Buffers_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\"}",
     "legendFormat": "buffer"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\", device=\"/dev/mapper/vgubuntu-root\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\", device=\"/dev/mapper/vgubuntu-root\", mountpoint=\"/\"}",
     "legendFormat": "available"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\",device=\"/dev/mapper/vgubuntu-root\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\",device=\"/dev/mapper/vgubuntu-root\",mountpoint=\"/\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate (node_network_receive_bytes_total{job=\"exporter\",instance=\"192.168.11.130:9100\"}[5m])",
     "legendFormat": "{{device}} recieved"
    },
    {
     "expr": "irate (node_network_transmit_bytes_total{job=\"exporter\",instance=\"192.168.11.130:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk Space in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (node_filesystem_avail_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\",device=\"/dev/mapper/vgubuntu-root\",mountpoint=\"/\"}) / (node_filesystem_size_bytes{job=\"exporter\",instance=\"192.168.11.130:9100\",device=\"/dev/mapper/vgubuntu-root\",mountpoint=\"/\"})",
     "legendFormat": "used"
    }
   ]
  }
 ]
}