{
 "title": "Host-Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "varlogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"varlogs\"} |= ``"
    }
   ]
  },
  {
   "title": "syslogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/syslog\"} |= ``"
    }
   ]
  },
  {
   "title": "varlogs - Docker",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"varlogs\"} |= `docker`"
    }
   ]
  },
  {
   "title": "varlogs - Errors",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"varlogs\"} |= `error`"
    }
   ]
  }
 ]
}